openapi: 3.0.0
info:
  title: Product Service API
  description: API for managing products in the AWS Shop
  version: 1.0.0
servers:
  - url: https://jco1jj7ev7.execute-api.eu-north-1.amazonaws.com/prod
    description: Production server
paths:
  /products:
    get:
      summary: Get all products
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProductRequest"
      responses:
        "201":
          description: Product created
        "400":
          description: Invalid input
  /products/{productId}:
    get:
      summary: Get product by ID
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Product not found
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        price:
          type: number
        count:
          type: number
          description: "Quantity in stock"

    CreateProductRequest:
      type: object
      required: [title, description, price, count]
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
        count:
          type: number
